spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  sql:
    init:
      mode: always
#      data-locations: classpath:data-prod.sql

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50

    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

    defer-datasource-initialization: true

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLE}
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 35MB

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLE}

dotchi:
  openapi:
    dev-url: ${DEV_URL}

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

jwt:
  token:
    secret-key: ${SECRET_KEY}
    access-expiration-time: ${ACCESS_EXPIRATION_TIME}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
